package:
  name: "pyqint"
  version: "0.4.0"

source:
  git_rev: master
  git_url: https://github.com/ifilot/pyqint

requirements:
  host:
    - pip
    - python
    - setuptools
    - cython

  run:
    - python
    - numpy

test:
  requires:
    - numpy
    - setuptools
  source_files:
    - tests/*.py
  commands:
    - python tests/test_overlap.py
    - python tests/test_kinetic.py
    - python tests/test_nuclear.py
    - python tests/test_repulsion.py

about:
  home: https://github.com/ifilot/pyqint
  license: GPL3
  license_family: GPL
  summary: Python package for evaluating integrals of Gaussian type orbitals in electronic structure calculations
